import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Split('''
chry_ringbuffer.c
''')

path = [
    cwd 
]

CPPDEFINES = ['USE_STDPERIPH_DRIVER']

group = DefineGroup('Libraries/CherryRB', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
